In [1]:
import numpy as np
from utils import *
import time

a=np.array([[2,0,0],[2,2,0]])
b=np.array([[1,0,0],[1,1,0]])
for i, j in zip(a,b):
    print(i,j)
print(zip(a,b))
nparray_to_relative_pose2d(a, b)
c=np.hstack((np.zeros([7,2])[0],1))
a[0]=[1,1,1]
print(a)

[2 0 0] [1 0 0]
[2 2 0] [1 1 0]
[[1 1 1]
 [2 2 0]]


In [2]:
from utils import *
import numpy as np


target_poses=[Pose2D(x=-0.7, y=0., theta=0.),
              Pose2D(x=-1.5, y=-1., theta=0.),
              Pose2D(x=-1.3, y=0., theta=0.),
              Pose2D(x=-1.5, y=1., theta=0.),
              Pose2D(x=1.5, y=-1., theta=pi),
              Pose2D(x=1.3, y=0., theta=pi),
              Pose2D(x=1.5, y=1., theta=pi),]
pose2d_to_nparray(target_poses)

array([[-0.7       ,  0.        ,  0.        ],
       [-1.5       , -1.        ,  0.        ],
       [-1.3       ,  0.        ,  0.        ],
       [-1.5       ,  1.        ,  0.        ],
       [ 1.5       , -1.        ,  3.14159265],
       [ 1.3       ,  0.        ,  3.14159265],
       [ 1.5       ,  1.        ,  3.14159265]])

In [3]:
import numpy as np
from numpy.linalg import norm
import sympy as sp


p=np.array([[1,1,0],[1,2,0],[1,3,0]])
vb=np.array([0,0,0])

def reach_time(pa, pb, vb, va_max=0.5):
    '''
    for agent from position pa with constant speed va to
    reach ball from position pb with constant speed vb, 
    calculate the shortest time
    '''
    ba=pa-pb # vector b to a
    t=sp.Symbol('t')
    solutions=sp.nonlinsolve([(va_max**2-norm(vb)**2)*t**2 + 2*t*np.dot(ba, vb) - norm(ba)**2],[t])
    t=1000
    for s in solutions:
        print(s[0])
        if s[0]>0 and s[0]<t:
            t=s[0]
    # t=next(iter(solutions))[0]
    p0=pb+vb*t
    return t, p0

def find_closest(p, vb):
    '''
    p: poses, ball at 0, 1~6 is robomaster
    vb: ball velocity
    '''
    pb=p[0]
    t_min=1000.
    p0=np.array([0,0])
    id=0
    print('p',p)
    for i in range(1, len(p)):
        print(p[i], pb, vb)
        t, p0=reach_time(p[i], pb, vb)
        
        if 0< t < t_min:
            t_min, p0, id=t, p, i
            print('---',i,'tmin p0 id')
            print(t_min, p0, id)
            print('p',p)
        
    return id, t_min, p0

find_closest(p,vb)


p [[1 1 0]
 [1 2 0]
 [1 3 0]]
[1 2 0] [1 1 0] [0 0 0]
-2.00000000000000
2.00000000000000
--- 1 tmin p0 id
2.00000000000000 [[1 1 0]
 [1 2 0]
 [1 3 0]] 1
p [[1 1 0]
 [1 2 0]
 [1 3 0]]
[1 3 0] [1 1 0] [0 0 0]
-4.00000000000000
4.00000000000000


(1, 2.00000000000000, array([1, 1, 0], dtype=object))

In [4]:
import re
a={}
a[1]='s'
a
re.sub('\D', '', str([1,2,3]))

'123'

In [6]:
tp=np.array([[-0.7       ,  0.        ,  0.        ],
                [-1.5       , -1.2        ,  0.        ],
                [-1.4       ,  0.        ,  0.        ],
                [-1.5       ,  1.2        ,  0.        ],
                [ 1.5       , -1.2        ,  pi],
                [ 1.4       ,  0.        ,  pi],
                [ 1.5       ,  1.2        ,  pi]])
target_poses=tp.copy()
team_a=[1,3,5]
team_b=[4,2,6]
for i in range(len(team_a)):
    target_poses[team_a[i]]=tp[i]
for i in range(len(team_b)):
    target_poses[team_b[i]]=tp[i]

7